language: c
sudo: false

branches:
  only:
    - master

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true

before_script:
  # Mimic X display
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - conda config --add channels omnia
  - conda config --add channels ${ORGNAME}
  - conda build devtools/conda-recipe
  - source activate _test
  # Run nosetests
  - cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer
  - cd ..
  # Run IPython notebook tests
  - source devtools/travis-ci/ipythontests.sh

env:
  matrix:
    # Changes to CONDA_NPY needed for pymc binstar availability.
    - python=2.7  CONDA_PY=27  CONDA_NPY=19
    #- python=2.7  CONDA_PY=27  CONDA_NPY=16
    #- python=3.3  CONDA_PY=33  CONDA_NPY=17
    #- python=3.4  CONDA_PY=34  CONDA_NPY=18

  global:
    - ORGNAME: "choderalab"
    - PACKAGENAME: "assaytools"
    # TODO: add encrypted AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to push documentation to S3
    # binstar
    - secure: "x/7fFUnTGXdQOiAduc8ONAiVOV63vgup1y4heemW/Z1fnhjAgNIjwIX0/9cJtV0HU7ayLXaBcMy6Bq72W49wIKZM6omvx6sazZ6ju0EUrp6GKQmZqio255cV2RA810uSTpNh2lIwkMPWfWfv2VmBzKsJyM4eKHrVdKsLUCGu7M4="

after_success:
  - echo "after_success"
  - ./devtools/travis-ci/after_success.sh
