package:
  name: assaytools-dev
  version: 0.0.0

source:
  path: ../..

build:
  entry_points:
    - xml2png = assaytools.scripts.xml2png:entry_point

requirements:
  build:
    - setuptools
    - python
    - numpy
    - pandas
    - scipy
    - pymc ==2.3.4
    - matplotlib
    - seaborn
    - lxml
    - ipython
    - notebook
    - autoprotocol
    - mock

  run:
    - python
    - numpy
    - pint
    - pandas
    - scipy
    - pymc
    - matplotlib
    - seaborn
    - lxml
    - ipython
    - notebook
    - autoprotocol
    - libgfortran ==1.0.0 [linux]

test:
  requires:
    - nose
    - pip
    - nose-timer
    - scripttest
    - ipython
    - notebook
    - ipynbtest
  imports:
    - assaytools

about:
  home: http://assaytools.choderalab.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A library for the modeling and analysis of plate-based assays (development snapshot)
